version: "3.8"
name: obs_stack
services:
  api:
    build: ..
    container_name: obs_demo_api
    environment:
      PORT: "8080"
      SERVICE_NAME: "demo-api"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
      LOG_LEVEL: "INFO"
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:0.95.0
    container_name: obs_otel_collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - "4318:4318"  # OTLP HTTP
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.53
    container_name: obs_jaeger
    ports:
      - "16686:16686" # UI
      - "14250:14250" # gRPC ingest

  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: obs_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.3.3
    container_name: obs_grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
